---
title: "DataFest"
toc: true
---

`.qmd` **TEMPLATE HERE!!!!**

{{< downloadthis datafest_template.qmd dname="datafest" label="datafest" id=mtcars-btn >}}

## Brief description

Over the weekend of April 4-6, you will work with a completely new-to-you dataset to answer some research question(s) of interest! More details on the [Middlebury DataFest website](https://midd-datafest-2025.github.io/)!

In small groups, you will work to answer the research question(s) of interest using methods we've thus far learned in the class.

Because of the extra time-commitment of DataFest, the problem set associated with Week 7 will be light or maybe combined into a problem set with Week 8!

## Key dates

+----------------------------------+-------------------------------------------------------------------------------------------------------------+--------------------------------------------------+
| Deliverable                      | What/where                                                                                                  | Date                                             |
+==================================+=============================================================================================================+==================================================+
| Group formation                  | Email Prof. Tang (one per group)                                                                            | Thursday 3/27 at 11:59pm                         |
+----------------------------------+-------------------------------------------------------------------------------------------------------------+--------------------------------------------------+
| Register for DataFest            | [DataFest website](https://midd-datafest-2025.github.io/home.html), "Register" tab (each person must do so) | Monday 3/31 in class                             |
+----------------------------------+-------------------------------------------------------------------------------------------------------------+--------------------------------------------------+
| DataFest opening ceremony        | Q-Center (MBH 202)                                                                                          | Friday 4/4 at 6:00pm                             |
+----------------------------------+-------------------------------------------------------------------------------------------------------------+--------------------------------------------------+
| Work on DataFest project         | Q-Center (MBH 202)                                                                                          | Anytime from opening ceremony-Sunday 4/6 11:00am |
+----------------------------------+-------------------------------------------------------------------------------------------------------------+--------------------------------------------------+
| Submit deliverable               | Rendered `.qmd` report submitted to **Canvas** (one per group!)                                             | Sunday 4/6 11:00am                               |
+----------------------------------+-------------------------------------------------------------------------------------------------------------+--------------------------------------------------+
| Project presentations (optional) | Q-Center (MBH 202)                                                                                          | Sunday 4/6 11:00am-12:00pm or 12:00pm-1:00pm     |
+----------------------------------+-------------------------------------------------------------------------------------------------------------+--------------------------------------------------+

## Requirements

### Group creation

You will work in groups of 2-3 people.

By the due date listed in the table above, you should either:

1.  form a group of three on your own and then e-mail Prof. Tang your decision, cc-ing everyone in the group
2.  form a group of two and then e-mail Prof. Tang your decision, cc-ing the other person in the group.
    -   Your group of two may be randomly paired with another person
3.  e-mail Prof. Tang if you don't have a preference and/or want to meet new people and would like to be randomly placed in a group

**While not binding, you should view the people you work with on DataFest as people who you might like to work on the final project with.**

Once all groups have been formed, Prof. Tang will confirm them and we will register for DataFest as a class on Monday 3/31.

### DataFest participation

-   You must attend the DataFest opening ceremony on Friday 4/4 at 6:00pm in the Q-Center. At the ceremony you will learn about the data and the research questions

-   **In addition to the opening ceremony, it is my expectation that your group works for at least 3 hours on the project over the course of the weekend.**

    -   Your whole group need not work together at the same time, but I highly encourage it all the same!

    -   Your are certainly welcome to work more than 3 hours!

-   There will be plenty of mentors on-site to help you will bugs. Prof. Tang will specifically be there at times TBD.

-   You will be asked to sign-up to present your finalized product to a panel of judges on Sunday 4/6 somewhere between 11am-1pm. Your entire group should attend the presentations (more details below).

### Report

You will be asked to create and submit a well-written report (in the form a rendered `.qmd`) that answers some or all of the research question(s) using a mix of both of the following methods:

1.  Compelling visualizations and summary tables, and

2.  Simulation-based inference techniques

Your report should include:

1.  A brief introduction that includes the research question(s) you plan on answering.
2.  For each research question of interest:
    i.  Details of cleaning/wrangling of the data you performed to answer the question
    ii. A description of the methods you used to answer the question
    iii. The actual result+interpretation in context (e.g. a visualization, confidence interval, conduct hypothesis test)
3.  A brief conclusion about what you might do differently or things that were particularly challenging
4.  A brief description of each person's contribution.

**You report should be submitted to Canvas. One per group!**

## Grading

This is meant to be a fun and low-stakes assignment that assess your ability to clearly convey a statistical analysis. The report will be graded as follows:

+---------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+
| What                                  | Details                                                                                                                                                                                                                                                           | Points |
+=======================================+===================================================================================================================================================================================================================================================================+========+
| Introduction                          | Includes a brief paragraph introducing any and all data used in the analysis. Also clearly states the research question(s) you plan on answering.                                                                                                                 | 1.5    |
+---------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+
| Data cleaning + wrangling description | Clearly explains how the data were manipulated for the analyses that are subsequently performed, and why you manipulated the data in such a way. This should be at a level of detail where someone could reproduce your cleaning without seeing your actual code. | 3      |
+---------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+
| Methodology                           | Describes methods used to answer the research question(s) and gives adequate justification for why the method is appropriate.                                                                                                                                     | 3      |
+---------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+
| Visualization/table + Interpretation  | Compelling and rich. Do not settle for a simple univariate visualization or a frequency table.                                                                                                                                                                    | 3      |
|                                       |                                                                                                                                                                                                                                                                   |        |
|                                       | Interprets the visualization with enough detail that someone who is unfamiliar with the data can understand it.                                                                                                                                                   |        |
+---------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+
| Inference technique + interpretation  | Correctly applies the inference techniques that were described in the methods.\                                                                                                                                                                                   | 4      |
|                                       | \                                                                                                                                                                                                                                                                 |        |
|                                       | Interprets the results in the context of the research question.                                                                                                                                                                                                   |        |
+---------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+
| Conclusion                            | Includes a brief concluding paragraph about what could be done differently.                                                                                                                                                                                       | 1.5    |
+---------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+
| Writing style                         | Clear writing with very few grammatical errors.                                                                                                                                                                                                                   | 2      |
+---------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+
| Reproducibility                       | Code is as reproducible as possible. This includes setting seeds and not "hard-coding" values.                                                                                                                                                                    | 2      |
+---------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+
| **Total**                             |                                                                                                                                                                                                                                                                   | 20     |
+---------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+

These 20 points will be divided by 4 and then incorporated into the your individual final project score. The final project will be out of 125 points. So a 0 on the DataFest project means you could obtain at most 120/125 $\approx 96\%$ on the final project. Once again, I emphasize that this project is low stakes but good practice for the final project!

### **Extra credit opportunity**

Your project need not only use the methods/functions we've learned in this class. Depending on the question/data you work with, you may need or want to teach yourself something new. Groups that successfully teach themselves and/or implement at least one of the following will be eligible for some extra credit points that will count towards Midterm 1. The list is not exhaustive:

-   Wrangling dates and times using `lubridate`
-   Wrangling text data using `tidytext`
-   Visualizing maps/spatial data using `geom_sf`
-   Create `ggplot()`s that use at least two different data frames and `geom_xx()` functions
-   Create an innovative, multivariate visualization that we have not seen as a class

While there will be mentors at DataFest who can help you, you should take the responsibility of using the internet to learn about some of these methods. Prof. Tang reserves that right to ask clarification questions about any and all code that is in your report.
