---
title: "Introduction to Statistical and Data Sciences"
---

Welcome to the website for Middlebury College’s Fall 2025 STAT 201A. On this website you will find the course syllabus, schedule, and assignments. The website is frequently updated throughout the semester, so please make a habit of refreshing the page. The icons at the top right will link to the supplemental textbook and Canvas.

------------------------------------------------------------------------

## Announcements

-   Welcome back!

-   SDS experience due tonight at midnight!

-   Midterm 2 revisions due beginning of class Wednesday 12/03

    -   Problems eligible for revision: 2d, 3c, 4, 5, and 8. You only need to do the specific part of the problem. However, if you part of your solution depends on the answer in a previous part which was wrong, you should also re-do that previous part

        -   For #8: explain why the new answer is the correct one.

    -   Please attach your revisions to your original midterm. Only work by yourself or consult Prof. Tang. You should sign the honor code on your revisions as acknowledgement that you adhere to this policy, otherwise no points back!

## Course details

**Instructor:** Prof. Becky Tang (she/her)

-   Office: WNS 214
-   Email: btang\@middlebury.edu

**Meeting times and location:**

-   MW 8:15am-9:30am in Munroe 311
-   R 8:15am-9:30am in Warner 105

**Office hours**: Monday 2-3pm, Friday 11am-12pm in common room outside Warner 214

**TA hours** in Q-Center (MBH 202):

-   Sunday, Monday, and Thursday 7-9pm

The [syllabus](stat201syllabus.pdf) (most recent update: 9/01/25) outlines our course policies and a rough schedule. Once classes begin, you should follow the schedule and due dates found on this website.

-   Note the textbooks are optional in this class. However, several practice and homework problems are pulled from the OpenIntro textbook.
