---
title: "Midterms"
format: 
  html:
    css: styles.css
    toc: true
---

## Midterm 2

### Logistics

-   **When and where**: Thursday, 11/20 during class (8:15-9:30am) in WNS 105

-   **What**: content through end of Week 10 (i.e. through Simple Linear Regression)

    -   You are allowed to bring a single, one-sided 8.5x11 inch piece of paper as your note sheet. **Your note sheet cannot have any example problems.** You will submit your note sheet alongside your midterm. No other outside resources besides your note sheet will be allowed.
    -   **I will provide a calculator to you for the midterm**. You are not allowed to use your own.
    -   You will be provided a table [z](z_table.pdf), [t](t_table.pdf), and [$\chi^2$](chi_square_table.pdf) table. We will familiarize ourselves with them in class prior to the midterm.
    -   There won't be any wrangling/ggplot coding assessed on this midterm, but you will have to feel comfortable with the `pnorm(), pt(), pchisq(), qnorm(), qt()` functions and how to use them.
    -   This midterm will focus on content from Week 5-Week 10, but some concepts do rely on content from first part of semester (e.g. random sampling, summary statistics, independence)

### Preparation

-   Come to office hours!
    -   **Extra office hours**: TBD
-   My personal working strategy:
    1.  First review your notes and homework
    2.  Make a first draft of your note sheet, then do some practice problems using only your note sheet to see if what you wrote on it is actually useful for you
    3.  Make a new note sheet
    4.  Repeat as necessary
-   Extra practice problems will be made available here.
-   You should make sure you understand how to read the distribution tables. Prof. Tang will not be able to help you read them during the midterm.

------------------------------------------------------------------------

## Midterm 1

### Revision opportunity

You have the opportunity of revising your midterm. Write your corrections, clearly indicating each problem, on a separate sheet of paper. For:

-   Problem parts that are written, simply provide a new solution with sufficient detail

-   For multiple choice and true/false, provide the new selection along with a reason why your new selection is correct. It may be helpful to also include why your previous solution was incorrect.

Please submit your corrections **stapled** to your original midterm to Prof. Tang **by Friday, 10/17 at 5pm.** If she isn't in the office, drop off your corrections in the box that will be left outside her office door.

**Important notes**:

-   You should not consult any resource besides your class notes, material on our course website, or Prof. Tang as you do the corrections. *Consulting any other person or resource will be viewed as a violation of the honor code.*

-   Incorrect revisions will lead to a deduction in points.

### Logistics

-   **When\* and where**:

    -   Oral component: Wednesday 10/08-Thursday 10/09, sign up for 15-minute block here: <https://calendly.com/beckytang/1-1-with-prof-tang>. Meet *promptly* at your scheduled time at Prof. Tang's office (WNS 214)

    -   Written component: Thursday, 10/09 during class

    -   **NOTE:** no class on Wednesday 10/08. This time will be used for oral component.

    -   **\*NOTE:** the syllabus originally had the written part of midterm on Wednesday, but I've moved the written part to the following day. I hope this is okay!

-   **What**: content through end of Week 4 (i.e. through Simpson's Paradox)

    -   This includes homework and coding practices
    -   Written component: Focus on non-programming content. You will not have to produce your own code, but you may have to read code/discuss coding concepts.
        -   **Plan to bring a calculator to the written component. I will also have some extra calculators in case you don't have one or forget to bring one!**
    -   Oral component: Focus on programming content. You will be given a prompt and have to discuss solution strategies and tell Prof. Tang what to type. You may be also be asked to interpret our findings.
        -   Prof. Tang is there to assist (to make sure we can make progress on the prompt), but part of your grade depends on how much you can independently produce!
        -   The rubric is provided [here](https://docs.google.com/document/d/1rf4G0R4Ty0m-9LmnwKEQjsp7opCi3-qXdmqcSxpvrvI/edit?usp=sharing)

-   You will not have a problem set assigned the week of the midterm!

-   **Extra office hours**: Tuesday 10/07 from 1-2pm

### Preparation

-   The best preparation you can do for the midterm is to go through your homework and coding practices and be honest with yourself about what you do/don't understand. This means going through the painful process of looking at feedback on Gradescope. For the concepts that you need to practice more, try more problems (see below)!

-   I suggest going through each of the `ggplot` and `dplyr` functions that we've seen in the course and ensuring you know how they work and when to use them!

-   **For extra practice for the written component**, I have made some extra review problems provided below. These are by no means exhaustive; there may be topics on the midterm that aren't covered in these problems.

    -   [Review problems](midterms/midterm1_review.pdf)

-   **For extra practice for the oral component**, additional coding problems are made available below. These questions are not necessarily representative of the typical scope and difficulty of individual exam questions (some are easier, some are harder). This review is not comprehensive.

    -   Practice 1: [Instructions](midterms/midterm1_practice1_rendered.pdf) and {{< downloadthis midterms/midterm1_practice1.qmd dname="midterm1-practice1" label=".qmd" id=mtcars-btn >}}

        -   Possible [solution](midterms/midterm1_practice1_solns.pdf)

    -   Practice 2: [Instructions](midterms/midterm1_practice2_rendered.pdf) and {{< downloadthis midterms/midterm1_practice2.qmd dname="midterm1-practice2" label=".qmd" id=mtcars-btn >}}

        -   Possible [solution](midterms/midterm1_practice2_solns.pdf)

    -   Practice 3: [Instructions](midterms/midterm1_practice3_rendered.pdf) and {{< downloadthis midterms/midterm1_practice3.qmd dname="midterm1-practice3" label=".qmd" id=mtcars-btn >}}

        -   Possible [solution](midterms/midterm1_practice3_solns.pdf)
