---
title: "Schedule"
page-layout: full
editor: 
  mode: source
format: 
  html:
    css: styles.css
---

**Jump to:**

<table>
  <tbody>
    <tr>
    <td> <a href="#week1">Week 1</a> </td>
    <td> <a href="#week2">Week 2</a> </td>
    <td> <a href="#week3">Week 3</a> </td>
    <td> <a href="#week4">Week 4</a> </td>
    <td> <a href="#week5">Week 5</a> </td>
    <td> <a href="#week6">Week 6</a> </td>
    <td> <a href="#week7">Week 7</a> </td>
    <td> <a href="#week8">Week 8</a> </td>
    <td> Week 9 </td>
    <td> Week 10 </td>
    <td> Week 11 </td>
    <td> Week 12 </td>
    </tr>
  </tbody>
</table>

<table>
  <thead>
    <tr>
      <th>Week</th>
      <th>Date</th>
      <th>In-class material</th>
      <th>Coding practice</th>
      <th>Assignments</th>
    </tr>
  </thead>
  <tbody>
  <!-- week 1 -->
    <tr>
      <td id="week1"><strong>1</strong></td>
      <td>M 9/08</td>
      <td>
        <ul>
          <li>Topic: <a href="slides/slides-00-welcome.qmd">Welcome!</a></li>
          <li>Directions for printing at bottom</li>
        </ul>
      </td>
      <td></td>
      <td>
        <ul>
          <li>Submit <a href="homework/hw0.qmd">Problem Set 0</a> <strong>by tomorrow 9/09 11:59pm</strong> class</li>
          <li>Try to install R and RStudio <strong>before Thursday's 9/11 class</strong> using <a href="slides/installation_instructions.qmd">these instructions</a></li>
        </ul>
      </td>
    </tr>
    <tr>
      <td></td>
      <td>W 9/10</td>
      <td>
        <ul>
          <li>Topic: Study design <a href="slides/slides-01-study-design.qmd">Study design</a>
          (pdf <a href="slides/pdf/slides-01.pdf">here</a>)
          </li>
          <!--
          <li><a href="practice_probs/practice-01-study-design.qmd">Practice problems</a></li>
          -->
        </ul>
      </td>
      <td></td>
      <td>
        <ul>
          <li>Install R and RStudio <strong>before Thursday class</strong> using <a href="slides/installation_instructions.qmd">these instructions</a></li>
          <li>Wednesday problems on <a href="homework/hw1.pdf">Problem Set 1</a></li>
        </ul>
      </td>
    </tr>
    <tr>
      <td></td>
      <td>R 9/11</td>
      <td>
        <ul>
          <li>Topic: <a href="slides/slides-02-toolkit.qmd">Programming toolkit</a> (no need to take notes!)</li>
          <ul>
            <li><a href="slides/02-rstudio_help_sheet.qmd">RStudio help sheet</a></li>
          </ul>
          <li><code>R</code> and <code>.qmd</code> <a href="live_code/intro_R.qmd">basics</a></li>
          <ul>
            <li>Download the following `.qmd` template and drag to your new STAT 201 folder {{< downloadthis live_code/template_intro_R.qmd dname="intro_R" label="Intro to R template" id=mtcars-btn >}}</li>
          </ul>
        </ul>
      </td>
      <td>
      <ul>
        <li>Intro to R and Quarto Markdown. <b>Due Friday 9/12 at 11:59pm!</b>         {{< downloadthis coding_practice/coding-practice-02-intro-r.qmd dname="coding-practice-intro-R" label="Coding practice" id=mtcars-btn >}}</li>
      </ul>
      </td>
      <td>
        <ul>
          <li>Thursday problems on <a href="homework/hw1.pdf">Problem Set 1</a></li> 
        </ul>
      </td>
    </tr>
    <!-- week 2 -->
    <tr>
      <td id="week2"><strong>2</strong></td>
      <td>M 9/15</td>
      <td>
        <ul>
          <li>Topic: <a href="slides/slides-03-numerical-pt1.qmd">Numerical data (part 1)</a>
          (pdf <a href="slides/pdf/slides-03.pdf">here</a>)
          </li>
            <ul>
              <li>Code: <a href="live_code/numerical_pt1.qmd">here</a>
              </li>
            </ul>
        </ul>
      </td>
      <td></td>
      <td>
        <ul>
          <li>Monday problems on <a href="homework/hw2.pdf">Problem Set 2</a></li>
        </ul>
      </td>
      </tr>
    <tr>
      <td></td>
      <td>W 9/17</td>
      <td>
        <ul>
          <li>Topic: <a href="slides/slides-04-numerical-pt2.qmd">Numerical data (part 2)</a>
          (pdf <a href="slides/pdf/slides-04.pdf">here</a>)
          </li>
        </ul>
      </td>
      <td>
      <ul>
        <li>Numerical data. <b>Due tonight at 11:59pm!</b>         {{< downloadthis coding_practice/coding-practice-04-numerical-pt2.qmd dname="coding-practice-numerical" label="Coding practice" id=mtcars-btn >}}</li>
      </ul>
      </td>
      <td>
        <ul>
          <li>Wednesday problems on <a href="homework/hw2.pdf">Problem Set 2</a></li>
        </ul>
      </td>
    </tr>
    <tr>
      <td></td>
      <td>R 9/18</td>
      <td>
        <ul>
          <li>Topic: <a href="slides/slides-05-numerical-data-viz.qmd">Introduction to ggplot</a>
          (pdf <a href="slides/pdf/slides-05.pdf">here</a>)
          </li>
          <ul>
            <li> `.qmd` template to follow live code {{< downloadthis live_code/live_code_notes.qmd dname="live_code_notes" label="Live code" id=mtcars-btn >}}</li>
          </ul>
        </ul>
      </td>
      <td>
      <ul>
          <li>Introduction to ggplot {{< downloadthis coding_practice/coding-practice-05-ggplot.qmd dname="coding-practice-ggplot" label="Coding practice" id=mtcars-btn >}}
          </li>
      </ul>
      </td>
      <td>
        <ul>
          <li>Thursday problems on <a href="homework/hw2.pdf">Problem Set 2</a>, i.e. the problems in the following `.qmd` {{< downloadthis homework/hw2_r.qmd dname="homework2_R" label="hw2_R" id=mtcars-btn >}}</li>
          <ul>
            <li> For easier reading: the <a href="homework/hw2_r.qmd">rendered `R` problems<a/></li>
          </ul>
        </ul>
      </td>
    </tr>
    <!-- week 3 -->
    <tr>
      <td id="week3"><strong>3</strong></td>
      <td> M 9/22 </td>
      <td>
        <ul>
          <li> Topic: <a href="slides/slides-06-categorical-data.qmd">Categorical data</a>
          (pdf <a href="slides/pdf/slides-06.pdf">here</a>) 
          </li>
        </ul>
      </td>
      <td>
        <ul>
          <li>Visualizing categorical data in ggplot {{< downloadthis coding_practice/coding-practice-06-categorical.qmd dname="coding-practice-categorical" label="Coding practice" id=mtcars-btn >}}
          </li>
        </ul>
      </td>
      <td>
        <ul>
          <li>Monday problems on <a href="homework/hw3.pdf">Problem Set 3</a></li>
        </ul>
      </td>
    </tr>
    <tr>
      <td></td>
      <td> W 9/24 </td>
      <td>
        <ul>
          <li> <a href="partner.qmd">Partner programming</a>: Activity 1
          </li>
          <li>  
            Topic: <a href="slides/slides-07-wrangling.qmd">Data wrangling</a> (pdf <a href="slides/pdf/slides-07.pdf">here</a>)
<div class="code-copy-container">
  <pre class="code-box"><code id="code1">url_file <- "https://raw.githubusercontent.com/midd-stat201a-fall25/midd-stat201a-fall25.github.io/refs/heads/main/data/amazon_books.csv"</code></pre>
  <button class="copy-button" onclick="copyToClipboard('code1')">Copy</button>
</div>
          </li>
          <li> Live code <a href="live_code/data_wrangling_pt1_class.qmd">from today</a>
          </li>
        </ul>
      </td>
      <td>
        <ul>
          <li>Data wrangling practice <b>(due tomorrow night!)</b> {{< downloadthis coding_practice/coding-practice-07-wrangling.qmd dname="coding-practice-wrangling" label="Coding practice" id=mtcars-btn >}} Note: 0, 3 and 4 are doable after today! </li>
        </ul>
      </td>
      <td>
        <ul>
          <li>Wednesday problems in <a href="homework/hw3.pdf">Problem Set 3</a> {{< downloadthis homework/hw3_r.qmd dname="homework3_R" label="hw3_R" id=mtcars-btn >}}</li>
          <li><a href="homework/hw3_r.qmd">Rendered version</a> of `.qmd` template for easier reading!</li>
        </ul>
      </td>
    </tr>
    <tr>
      <td></td>
      <td> R 9/25 </td>
      <td>
        <ul>
          <li> <a href="partner.qmd">Partner programming</a>: Activity 2 </li>
          <li> Topic: More wrangling </li>
          <ul>
            <li>Live code <a href="live_code/data_wrangling_pt2_alex.qmd">from today</a></li>
            <li><a href="live_code/data_wrangling_pt2_new.qmd">Extra code with descriptions!</a></li>
          </ul>
        </ul>
      </td>
      <td>
        <ul>
          <li>Finish data wrangling coding practice</li>
        </ul>
      </td>
      <td>
        <ul>
          <li>Thursday problems in <a href="homework/hw3.pdf">Problem Set 3</a></li>
        </ul>
      </td>
    </tr>
    <!-- week 4 -->
    <tr>
      <td id="week4"><strong>4</strong></td>
      <td> M 9/29 </td>
      <td>
        <ul>
          <li><a href="partner.qmd">Partner programming</a>: Activity 3</li>
          <li> Topic: <a href="slides/slides-09-probability.qmd">Intro to Probability</a> (pdf <a href="slides/pdf/slides-09.pdf">here</a>) 
          </li>
        </ul>
      </td>
      <td>
      </td>
      <td>
        <ul>
          <li>None for today; bigger set for Wednesday.</li>
        </ul>
      </td>
    </tr>
    <tr>
      <td></td>
      <td> W 10/01 </td>
      <td>
        <ul>
          <li> Introduce <a href="midterms.qmd">Midterm 1<a/> </li>
          <li> Topic: Finish <a href="slides/slides-09-probability.qmd">Intro to Probability</a> </li>
          <li> Topic: <a href="slides/slides-10-conditional-probability.qmd">Conditional Probability</a> (pdf <a href="slides/pdf/slides-10.pdf">here</a>) </li>
        </ul>
      </td>
      <td>
      </td>
      <td>
        <ul>
          <li>Wednesday problems in <a href="homework/hw4.pdf">Problem Set 4</a></li>
        </ul>
      </td>
    </tr>
    <tr>
      <td></td>
      <td> R 10/02 </td>
      <td>
        <ul>
          <li> Topic: Finish <a href="slides/slides-10-conditional-probability.qmd">Conditional Probability</a> </li>
          <li> Topic: <a href="slides/slides-11-simpsons.qmd">Simpson's Paradox</a> (pdf <a href="slides/pdf/slides-11.pdf">here</a>) </li>
<div class="code-copy-container">
  <pre class="code-box"><code id="code2">url_file <- "https://raw.githubusercontent.com/midd-stat201a-fall25/midd-stat201a-fall25.github.io/refs/heads/main/slides/data/ucb_admissions.csv"</code></pre>
  <button class="copy-button" onclick="copyToClipboard('code2')">Copy</button>
</div>
        </ul>
      </td>
      <td>
        <ul>
          <li> Joins, case_when, tables {{< downloadthis coding_practice/coding-practice-11-case_when.qmd dname="coding-practice-case-when" label="Coding practice" id=mtcars-btn >}} due tomorrow (10/03 at 11:59pm) </li>
        </ul>
      </td>
      <td>
        <ul>
          <li>Thursday problems in <a href="homework/hw4.pdf">Problem Set 4</a> {{< downloadthis homework/hw4_r.qmd dname="homework4_R" label="hw4_R" id=mtcars-btn >}} Note there was a typo in the .qmd; R Exercise 5 should read "Re-create your first visualization from Exercise 1"! </li>
          <li>Study for Midterm 1</li>
        </ul>
      </td>
    </tr>
    <!-- week 5 -->
    <tr>
      <td id="week5"><strong>5</strong></td>
      <td> M 10/06 </td>
      <td>
        <ul>
          <li><a href="partner.qmd">Partner programming</a>: Activity 4</li>
          <li> Topic: <a href="slides/slides-12-sampling-dist.qmd">Sampling distributions</a> (pdf <a href="slides/pdf/slides-12.pdf">here</a>) </li>
        </ul>
      </td>
      <td>
      </td>
      <td>
        <ul>
          <li>None! Ensure you sign up for oral midterm time slot.</li>
        </ul>
      </td>
    </tr>
    <tr>
      <td></td>
      <td> W 10/08 </td>
      <td>
        <ul>
          <li> No class! </li>
        </ul>
      </td>
      <td>
      </td>
      <td>
        <ul>
          <li>Study for midterm.</li>
        </ul>
      </td>
    </tr>
    <tr>
      <td></td>
      <td> R 10/02 </td>
      <td>
        <ul>
          <li> Midterm 1: written component </li>
        </ul>
      </td>
      <td>
      </td>
      <td>
        <ul>
          <li> None! Enjoy Fall break!</li>
        </ul>
      </td>
    </tr>
    <!-- week 6 -->
    <tr>
      <td id="week6"><strong>6</strong></td>
      <td> M 10/13 </td>
      <td>
        <ul>
          <li> Topic: <a href="slides/slides-13-bootstrap.qmd">Bootstrap</a> (pdf <a href="slides/pdf/slides-13.pdf">here</a>) </li>
          <ul>
            <li> <a href="live_code/bootstrap_dist_live.qmd">Code</a> </li>
          </ul>
        </ul>
      </td>
      <td>
      </td>
      <td>
        <ul>
          <li> Monday problems on <a href="homework/hw5.pdf">Problem Set 5</a> </li>
        </ul>
      </td>
    </tr>
    <tr>
      <td></td>
      <td> W 10/15 </td>
      <td>
        <ul>
          <li> Topic: <a href="slides/slides-14-bootstrap-ci.qmd">Bootstrap Confidence Intervals</a> (pdf <a href="slides/pdf/slides-14.pdf">here</a>) </li>
        </ul>
      </td>
      <td>
        <ul>
          <li> Bootstrap CIs {{< downloadthis coding_practice/coding-practice-14-bootstrap.qmd dname="coding-practice-bootstrap-ci" label="Coding practice" id=mtcars-btn >}} </li>
        </ul>
      </td>
      <td>
        <ul>
          <li> Wednesday problems on <a href="homework/hw5.pdf">Problem Set 5</a> {{< downloadthis homework/hw5_r.qmd dname="homework5_R" label="hw5_R" id=mtcars-btn >}}</li>
        </ul>
      </td>
    </tr>
    <tr>
      <td></td>
      <td> R 10/16 </td>
      <td>
        <ul>
          <li> Topic: <a href="slides/slides-15-intro-testing.qmd">Intro to Hypothesis Testing</a> (pdf <a href="slides/pdf/slides-15.pdf">here</a>) </li>
          <li> Handout <a href="slides/handout-15-intro-testing.qmd">here</a>
          </li>
        </ul>
      </td>
      <td>
      </td>
      <td>
        <ul>
          <li> Thursday problems on <a href="homework/hw5.pdf">Problem Set 5</a> </li>
        </ul>
      </td>
    </tr>
    <!-- week 7 -->
    <tr>
      <td id="week7"><strong>7</strong></td>
      <td> M 10/20 </td>
      <td>
        <ul>
          <li> Wrap-up previous slides </li>
          <li> Topic: <a href="slides/slides-16-randomization.qmd">Randomization tests</a> (pdf <a href="slides/pdf/slides-16.pdf">here</a>) </li>
          <ul>
            <li>  Handout <a href="slides/handout-16-randomization.qmd">here</a> </li>
          </ul>
        </ul>
      </td>
      <td>
      </td>
      <td>
        <ul>
          <li> Monday problems on <a href="homework/hw6.pdf">Problem Set 6</a> {{< downloadthis homework/hw6_r.qmd dname="homework6_R" label="hw6_R" id=mtcars-btn >}} </li>
          <li> A <a href="homework/hw6_r.qmd">rendered version</a> of the `.qmd` for easier reading.</li>
        </ul>
      </td>
    </tr>
    <tr>
      <td></td>
      <td> W 10/22 </td>
      <td>
        <ul>
          <li> Topic: Finish up randomization tests from Monday </li>
        </ul>
      </td>
      <td>
      </td>
      <td>
        <ul>
          <li> Continue working on Problem Set 6 </li>
        </ul>
      </td>
    </tr>
    <tr>
      <td></td>
      <td> R 10/23 </td>
      <td>
        <ul>
          <li> Topic: <a href="slides/slides-17-single-mean-shift.qmd">Simulation-based test for one mean</a> (pdf <a href="slides/pdf/slides-17.pdf">here</a>)
          </li>
          <li> Handout <a href="slides/handout-17-single-mean.qmd">here</a>
          </li>
        </ul>
      </td>
      <td>
      </td>
      <td>
        <ul>
          <li> Thursday problems on Problem Set 6 </li>
        </ul>
      </td>
    </tr>
    <!-- week 8 -->
    <tr>
      <td id="week8"><strong>8</strong></td>
      <td> M 10/27 </td>
      <td>
        <ul>
          <li> Topic: Normal distribution (no slides) </li>
          <ul>
            <li>  Handout <a href="slides/handout-18-normal.qmd">here</a> </li>
          </ul>
          <li> Introduce <a href="project/project_description.qmd">final project</a>! </li>
        </ul>
      </td>
      <td>
      </td>
      <td>
        <ul>
          <li> Monday problems on Problem Set 7 </li>
        </ul>
      </td>
    </tr>
    <tr>
      <td></td>
      <td> W 10/29 </td>
      <td>
        <ul>
          <li> Topic: Central Limit Theorem, CLT-based CI for single proportion </li>
          <ul>
            <li>  Handout </li>
          </ul>
        </ul>
      </td>
      <td>
      </td>
      <td>
        <ul>
          <li> Continue working on Problem Set 7 </li>
        </ul>
      </td>
    </tr>
    <tr>
      <td></td>
      <td> R 10/30 </td>
      <td>
        <ul>
          <li> Topic: CLT-based HT for single proportion
          </li>
          <ul>
            <li>  Handout </li>
          </ul>
        </ul>
      </td>
      <td>
      </td>
      <td>
        <ul>
          <li> Thursday problems on Problem Set 7 </li>
        </ul>
      </td>
    </tr>
  </tbody>
</table>


<script>
function copyToClipboard(elementId) {
  const code = document.getElementById(elementId).innerText;
  navigator.clipboard.writeText(code).then(function() {
    alert("Code copied to clipboard!");
  }, function(err) {
    alert("Failed to copy: ", err);
  });
}
</script>
