---
title: "Study design"
author: "Practice problems"
format: 
  pdf:
    keep-tex: true
    include-in-header:
      text: |
        \setkomafont{author}{\small}
        \setkomafont{date}{\small}
    geometry:
      - left=1in
      - right=1in
---

1.  In Spring 2024, Prof. Tang asked her STAT 311 students to fill out a mid-semester survey. She was particularly interested in the the amount of hours her STAT 311 students were spending per week on the course. Of the 90% of students who responded, the average time spent on the course was found to be 10.2 hours per week.

    Based on this information, identify which of the following correspond to a: case, variable, parameter, and statistic.

    -   10.2 hours
    -   The average number of hours spent on the course of all STAT 311 students from Spring 2024
    -   A STAT 311 student
    -   The number of hours spent on STAT 311

2.  Suppose we want to estimate household size, where a *“household”* is defined as people living together in the same dwelling, and sharing living accommodations. If we select students at random at an elementary school and ask them what their family size is, will this be a good measure of household size? Or will our average be biased? If so, will it overestimate or underestimate the true value?

3.  Chia seeds have gained reputation as a diet supplement. In one 2009 study, 38 men and 38 women were recruited (i.e. specifically chosen) and then divided randomly into two groups: treatment or control. One group was given 25 grams of chia seeds twice a day to consume, and the other was given a placebo. The seeds and placebo were designed to look the same. The subjects volunteered to be a part of the study. After 12 weeks, the scientists found no statistically discernible difference between the groups in appetite or weight loss.

    a.  What are the treatments in this study?
    b.  Is there any blinding?
    c.  Comment on whether we can make a causal statement, and indicate whether we can generalize the conclusions from this study to the population at large.

```{=html}
<!--
1.  We discussed several methods of sampling today. Now consider a new sampling scheme that is commonly used in the social sciences when sampling from a "hidden" population. A scenario might be that we want to conduct a poll among homeless people, but the research team may only have contact details for a few homeless people.

    Denote the initial contacts as Group 1. The sampling proceeds in the following stages:

    i.  Stage 1: ask the people in Group 1 to take the survey, and then provide contact details for other people from the population who might want to participate. Denote these new contacts as Group 2.
    ii. Stage 2: ask the people in Group 2 to take the survey, and then provide contact details for other people from the population who might want to participate. Denote these new contacts as Group 3.
    iii. Proceed in a similar manner until the researchers have sufficient data.

    <!-- -->

    a.  What are some advantages to this method of sampling?
    b.  What are some disadvantages? Think about statistically and also ethically.
-->
```
