---
title: "Project desciprtion old"
---

## Report

Each group will write a final report created in an `.qmd` file. You can download the template here:

{{< downloadthis stat201_final_project.qmd dname="stat201_final_project" label="template" id=mtcars-btn >}}

Example projects from Fall 2024:

-   [Example 1](f24_living_sleep.pdf)

-   [Example 2](f24_newengland_other.pdf)

Your report will be submitted both as a PDF and as a `.qmd` file. **The code in your report should be as reproducible as possible** (e.g. not hard coding specific values, setting a seed when appropriate). All tables should be beautiful!

**Additionally, only the output/execution from the code relevant for the report should be visible to the reader, not the code itself.** This means that as the viewer, I should not see any code or extraneous output. The former is achieved by setting the chunk header option `echo = F`. That being said, if there is some code that you believe is useful/important for the reader to see, you are welcome to make that code visible by setting `echo = T`.

The report does not have a minimum length, but should contain each of the following sections. *The report should also have an informative, academically appropriate title along with each group member's name.*

#### **Introduction**

-   The introduction should introduce your research questions and the population(s) of interest. **Your report should have at least one research question per team member**. In the introduction, you should briefly motivate the research questions (i.e. explain why they were of interest to your group)!
    -   It could be helpful to identify/label your research questions as "Question 1", "Question 2", etc. for easier reference moving forward.

#### **Data collection**

This section should describe your data and the sampling process: **how** the data were collected and a summary description of the variables you collected.

#### **Methods**

For **each** research question, you should:

1.  Identify the specific variables used to address the research question. Also describe if you had to create/mutate new variables or filter out/subset your analysis to focus on certain observations for this research question. For each analysis, please tell us the sample size you ended up with.

2.  Include at least one visualization or table of summary statistics that will be useful/informative for answering the research question. Briefly interpret the visualization/summary table.

    -   It is okay if if one visualization is complex enough to address multiple research questions!

3.  Describe and justify the statistical method(s) that you will use to answer your research questions. Part of the "justification" component includes conditions being met, if applicable. For linear regression, you should only verify the "L" and the "I" at this point.

    -   Be specific about different groups/populations, direction of differences, explanatory vs response variable, etc.

    -   If you are conducting a hypothesis test, don't forget to define your hypotheses and set the significance level. If you are creating a confidence interval, be sure to specify the level of confidence.

#### **Results**

-   Using appropriate code, conduct the statistical methods you described in the Methods section for each research question. Then interpret your results in context (i.e. use your interval/p-value/model to actually answer the question).
    -   If you do linear regression, you should check the "N" and "E" conditions here.
-   The goal is not to do an exhaustive data analysis (i.e., do not calculate every statistic and procedure you have learned for every variable), but rather let me know that you are proficient at asking meaningful questions and answering them with results of data analysis, that you are proficient in using R, and that you are proficient at interpreting and presenting the results.

#### **Discussion**

This section is a conclusion and discussion. This will require:

1.  A summary of what you have learned about your research questions along with statistical arguments supporting your conclusions.
2.  A critique your own methods and provide suggestions for improving your analysis. Issues pertaining to the reliability and validity of your data/data collection and appropriateness of the statistical analysis should also be discussed here.
3.  A paragraph on what your group would do differently if you were able to start over with the project or what you would do next if you were going to continue work on the project should also be included.

## Presentation

Each group will present their work during the exam period. Presentation duration lengths (before questions) are:

-   Groups of one: 5-7 minutes

-   Groups of two: 7-9 minutes

-   Groups of three: 9-11 minutes

Part of your presentation grade will be sticking to the presentation duration. Your presentation will be followed by a few minutes for questions from the audience.

Your presentation should be accompanied by **slides** that summarize and showcase your project. Introduce your research questions and data/data collection, showcase visualizations, and provide some conclusions. These slides should serve as a brief visual accompaniment and will be graded for content and quality. **I recommend roughly one slide per minute of your presentation.**

The slides are due to Canvas **one hour before our final exam/presentation period.**

-   You do not need to discuss all of your research questions if you don't want to! You are not expected to have finished all your analyses by the time you present, but you should have *some* results (whether preliminary or finalized).
-   It's most important that your audience understands the research questions you present, how you obtained your data, and how you plan to answer the research questions.
-   Pictures and summary tables are always preferred over sentences!
-   A general recommendation is to have one slide per minute of the presentation.
-   All presenters should speak roughly an equal amount of time.
-   Make sure the font is large enough. Also, less is more!

Part of the presentation component is participation. You should be an engaged audience member. You will be asked to give feedback to a few groups and you are expected to ask questions.

### Presentation order

1.  LeBronJames (Dylan, Owen)
2.  LeMiddDash (Arthur, Hayes, Tommy)
3.  No. (Natalie A., Calvin, Aaliyah)
4.  The Trash CAN (Naomi, Conor, Aidan)
5.  The Outlier (JuJu)
6.  Standard Deviants (Charlie, Haru, Luke)
7.  Minnie & Morgan
8.  CLIck (Lilah, Clio, Isa)
9.  I hate group names (Natalie O., Alden)

## Misc. submission items

### Finalized data set + dictionary

You will be asked to submit your finalized, clean dataset. This may take the form of a `.csv` file or a link to a GoogleSheet. Please give each variable an informative one-word name. Alongside the submission, please include a separate file for the **data dictionary**: a bulleted list or table containing each variable name, a brief description of the variable, and the variable type. Include units if appropriate. If the variable is categorical, please provide all the levels as they appear in the cleaned data.

The purpose of the data dictionary is to enable future use of your data.

### Reflection

You will be asked to write a brief reflection about the final project. There will be a few questions/prompts pertaining to your specific contribution, learning, and experience, along with an opportunity to comment on the group dynamics and working methods. The prompts/questions will be provided on the associated Canvas assignment.
